name : dailyrecord CI
on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name : Checkout repository
        uses : actions/checkout@v3
      
      - name : Set up Node.js ${{ matrix.node-version }}
        uses : actions/setup-node@v2
        with :
          node-version: ${{ matrix.node-version }}

      - name : Install client dependencies
        run : |
          cd client
          npm install

      - name : Install server dependencies
        run : |
          cd server
          npm install

      - name : Install outdir dependencies
        run : npm install

      - name : Build client
        run : |
          cd client
          CI=false npm run build

      - name : Open server
        run : |
          cd server
          npx pm2 start app.ts

      - name : Open client
        run : |
          cd client
          npx pm2 serve build 3000 client --spa

      - name : Deploy
        uses : appleboy/ssh-action@master
        with :
          host : ${{ secrets.SSH_REMOTE_IP }}
          username : ${{ secrets.SSH.REMOTE_ID }}
          key : ${{ secrets.SSH_SECRET_KEY }}
          port : 22

